import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]
[cursor]
style = "Beam"

[font]
size = 12

[env]
TERM = "xterm-256color"

[font.normal]
family = "Hack Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1

[window.padding]
x = 0
y = 0

#[window.dimensions]
#columns = 90
#lines = 25






[window.class]
general = "Alacritty"
instance = "Alacritty"
